### ISSUE TITLE
Save tag information 

### ISSUE THREAD

**Issue by gunzasun** [nadam/nfc-reader#15]
???

**Comment by Yangmomo1978** [comment]
Sorry, this is not my project.I just forked it.

2015-04-28 0:59 GMT+08:00 gunzasun <notifications@github.com>:

> How can I save the information (retrieved text information from the NFC
> tag) to the sql database.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nadam/nfc-reader/issues/15>.
>



-- 
王巍

**Comment by nadam** [comment]
You can copy/past tag data and there is a new menu option for saving several tags at once. I have problem updating the app on Google Play at the moment, but you can download the latest apk manually at https://github.com/nadam/nfc-reader/tree/master/market
