### ISSUE TITLE
Convert to Library

### ISSUE THREAD

**Issue by thegoatherder** [nadam/nfc-reader#17]
Hi Adam,

Thanks for sharing the code of your app. It makes an excellent case study.  I am planning to fork your code and refactor it slightly so that it can be used as a Library. Mainly I will be changing getView to getRecord.

I will give you full credit. I just wanted to check with you a couple of things:
1. Do you see it as a complete solution and if not what features are missing? I will add these to the backlog.
2. Would you prefer the repository was hosted on your account so that you get full credit and I am just a contributor?

Thanks from one Adam to another,
Adam.

**Comment by nadam** [comment]
Sorry for late reply. Most of the code in this project is from Google, so I don't see much need for taking credit. Feel free to do anything you want.

**Comment by dex2000** [comment]
looks like the fork is inactive, similar question for that (if i understand "library" correctly) here:

possibility to save scanned IDs in a library would be fine. is there any log for that or planned for the future?
