### ISSUE TITLE
tag technology support

### ISSUE THREAD

**Issue by ShrikantBadwaik-007** [nadam/nfc-reader#23]
I have a question related to this. Does this supports all tech technologies other than NDEF mentioned in Table 1 & 2 on Official Android Documentation [here](https://developer.android.com/guide/topics/connectivity/nfc/advanced-nfc.html)

**Comment by nadam** [comment]
Yes, all supported.

**Comment by shrikantbadwaik** [comment]
@nadam is there any 3rd party lib used for that purpose or referring to this repo will be enough because I'm developing nfc based app which require support for all nfc tech.

**Comment by shrikantbadwaik** [comment]
@nadam for non-ndef tag output is something like this
**ID(hex): 80 49 8f ea f8 a1 04
ID(reversed hex): 04 a1 f8 ea 8f 49 80
ID(dec): 36109679490277636
ID(reversed dec): 1303990366062976
Technologies: MifareUltralight, NfcA, Ndef
Mifare Ultralight type: Ultralight C**

but i'm not getting actual data tag contains. How do I get data from tag from above output?
