### ISSUE TITLE
How to get data from MRT card

### ISSUE THREAD

**Issue by SyedKabeer** [nadam/nfc-reader#24]
I am trying to read values from ez-link Singapore MRT card. Below image is my current output:
![current_output](https://user-images.githubusercontent.com/1648750/29816169-b596fefe-8ce5-11e7-8d8c-426fea0f35ac.jpg)

How fetch values like travel history/ current balance, refer below image:
![expected_output](https://user-images.githubusercontent.com/1648750/29816229-ee333a02-8ce5-11e7-8d44-fa515e83ab36.jpg)

**Comment by nadam** [comment]
I don't know.
