### ISSUE TITLE
Wrong data scanned

### ISSUE THREAD

**Issue by rakeshparveen5** [nadam/nfc-reader#29]
NFC tag after scaning shows this : 

80 58 99 9a 91 84 04
ID (reversed hex): 04 84 91 9a 99 58 80
ID (dec): 36126213765432324
ID (reversed dec): 1271660805707904
Technologies: NfcA, MifareUltralight, Ndef
Mifare Ultralight type: Ultralight C

**Comment by jellewie** [comment]
This isn't enough information for the owner to do anything about it.

try to answer these to in a bug report.
**What were you expecting?**

**What did you do? and how can it reliable be reproduced?**

**On what device and what version are you on?**

**Comment by rakeshparveen5** [comment]
I am trying to read a nfc tag on Samsung J3 pro device.After scanning , this result is returned

**Comment by jellewie** [comment]
> I am trying to read a NFC tag on Samsung J3 pro device. After scanning, this result is returned

This looks completely normal to me? Could you please explain what you were expecting? This app is able to read the raw HEX data of the (NfcA, MifareUltralight, Ndef) tag you are using, and if did do that?

**Comment by rakeshparveen5** [comment]
My tag contains some another data while I write it. But a the time of reading its not reading correct string

**Comment by jellewie** [comment]
> My tag contains some another data while I write it. But a the time of reading its not reading correct string

How did you write data to your tag? an other app? which one and how?

What data did you write to the tag? (and thus what did you expect to return)

This app reads the tags in hex format not in string format? would that maybe be your problem?

**Comment by rakeshparveen5** [comment]
Ok. lt me recheck the nfc write code . May be there is some thing 
Thanks @jellewie
