### ISSUE TITLE
Broken Google Play Store link

### ISSUE THREAD

**Issue by bird-dancer** [nadam/nfc-reader#33]
The link of the "Get it on Google Play" returns a 404 error on Google Play's website.
I also couldn't find the app by searching for it on the play store.

**Comment by jidanni** [comment]
I get "something went wrong".
I conclude those nobody in charge of this app anymore.

**Comment by SomeTroglodyte** [comment]
It's plainly visible that the last merge was 6 years ago. But for something as simple as this, you could always just build it yourself, should be easy enough.
