### ISSUE TITLE
Value of Tag ID (dec) is not correct

### ISSUE THREAD

**Issue by headshot9x** [nadam/nfc-reader#35]
When I scanned card with Tag ID (DEC) begin with number "0", app can not show it because mistake. So, kindly checking again. 
Sample: Tag ID (DEC) is " 0123456789", but when scan it, app just show Tag ID (Dec) is "123456789"

**Comment by jasti99** [comment]
> When I scanned card with Tag ID (DEC) begin with number "0", app can not show it because mistake. So, kindly checking again. 
> Sample: Tag ID (DEC) is " 5501439057", but when scan it, app just show Tag ID (Dec) is '5501439057"

**Comment by nadam** [comment]
The decimal number 123456789 is the same as 0123456789. Leading zeros don't change the value. Same thing with trailing zeroes at the end of a decimal number.
