### ISSUE TITLE
Where is the MainActivity?

### ISSUE THREAD

**Issue by BirdNum** [nadam/nfc-reader#36]
Would you please tell me where is the MainActivity.java? I can't build the APK in android studio(I hava find the whole project).

**Comment by nadam** [comment]
The main activity is called TagViewer in this project.
https://github.com/nadam/nfc-reader/blob/master/src/se/anyro/nfc_reader/TagViewer.java

**Comment by BirdNum** [comment]
Thank you very much,  I can already debug the app in android studio normally。
