### ISSUE TITLE
Forward the raw data to a port on the phone

### ISSUE THREAD

**Issue by sandys** [nadam/nfc-reader#7]
hi,
There is a very good usecase for using the phone's NFC reader on the desktop by connecting it with ADB and running a portforward.

For example, on the phone you could do 

echo Just testing' | nc -l -p 1112  #putting it on port 1112

on the desktop,
do a port forward "adb tcp:1111 tcp:1112"
read the data from port 1111 - nc 127.0.0.1 1111

Not only this, you could now get desktop apps to read from the forwarded port and have access to the NFC scan data.

Could you add a feature to push NFC scan _raw data_ to a port on android - you can hardcode this.

thanks!

**Comment by nadam** [comment]
Closing this issue since it's not likely to be implemented. There might be other apps out there doing this already.
